// src/app/pages/about/about.component.ts
import { Component } from '@angular/core';
import { DirectoresComponent } from './directores/directores.component';
import { HistoriaComponent } from './historia/historia.component';
import { BandaJuvenilComponent } from './banda-juvenil/banda-juvenil.component';

@Component({
  selector: 'app-about',
  imports: [DirectoresComponent, HistoriaComponent, BandaJuvenilComponent],
  templateUrl: './about.component.html',
  styleUrl: './about.component.css'
})
export class AboutComponent {

}

<body>
  <h1>Sobre nosotros</h1>
  <p>
    La Asociación Jumillana Amigos de la Música fue fundada en 1980 por un
    grupo de entusiastas jumillanos, con el apoyo del Excmo. Ayuntamiento de
    Jumilla, con el fin de ocupar el espacio musical dejado por la
    desaparecida Banda de Música Municipal.
  </p>
  <p>
    Una vez constituida la Asociación, se crea una Academia de Música y con
    los alumnos formados en esta, se crea la Banda de Música de la Asociación.
    Esta hace su presentación oficial, en Jumilla el 12 de Abril de 1981. Su
    primer director fue el compositor jumillano D. Julián Santos Carrión, a
    quien sucedería en 1982 D. José Bacigalupe Serrano, desde 1987 y hasta
    1996 dirigió la Academia y Banda de la Asociación D. Antonio Milán Juan,
    durante el año 1997 D. Sergio Fernández Diez-Picazo. En 1998 D. José Ant.
    Arce Corbalán. Del 1999 al 2004 la dirigió el músico y compositor
    georgiano D. Zurab Kala al que sucedió D. Julián Andreo Jiménez hasta
    noviembre de 2008. Desde diciembre de 2008, D. Mario Ortuño Gelardo es el
    director de la Banda de Música a sí como de su Academia hasta octubre de
    2015, año en el que entraría como director de la Banda de Música Titular
    Ángel Hernández Azorín.
  </p>
  <p>
    Desde su creación, la Banda ha desarrollado una intensa actividad musical,
    participando en numerosos ciclos de conciertos en la localidad, en toda la
    región de Murcia y las Regiones limítrofes de Castilla la Mancha y
    Valencia. Participa en varios programas radiofónicos de Radio Nacional de
    España: “A TODA BANDA” y “PLAZA MAYOR”, y en programas televisivos a nivel
    regional y nacional.
  </p>
  <p>
    En 1989 se forma la Banda de Música Juvenil, con el objetivo de preparar a
    los educandos de la Academia y los integrantes noveles de la Banda de la
    Asociación.
  </p>
  <p>
    Desde el año 1983, en el mes de noviembre la Asociación viene celebrando
    una semana cultural en honor a Santa Cecilia, con actuaciones de solistas
    y grupos de reconocido prestigio, tanto nacionales como extranjeros. En
    1993, se organiza el primer Festival de Bandas de Música, con la
    participación de dos bandas invitadas y la Banda de la Asociación,
    intentando mantener un alto nivel interpretativo de cada una de las
    agrupaciones participante y de las obras elegidas.
  </p>
  <p>Entre los mayores logros obtenidos cabe destacar:</p>
  <ul>
    <li>
      En los programas - concursos de televisión española “GENTE JOVEN” y
      “NUEVA GENTE”, quedando semifinalistas en el primero de ellos.
    </li>
    <li>
      En 1997 participa en el "Festival Internacional de Bandas de Música
      Villa Altea”, junto a otras bandas de Música con reconocido prestigio
      como el Ateneo Musical de Cullera y la Sociedad Musical de Alcira,
      obteniendo el tercer premio. En el 2001 participa en la 2º sección del I
      Certamen Nacional de Zarzuela para Bandas de Música organizado por la
      Fundación Nacional de la Zarzuela, obteniendo un 2º accesit.
    </li>
    <li>
      En el año 2003 participa en el I Certamen Regional de Bandas de la
      Región de Murcia, obteniendo un segundo premio en la 1ª sección y en el
      IV Certamen Internacional de Bandas de Música “Villa de Aranda”
      obteniendo el Premio Especial al Desfile. En el año 2005 participa en el
      II Certamen Regional de Bandas de la Región de Murcia, obteniendo un
      segundo premio en la 1ª sección.
    </li>
    <li>
      En Julio de 2008 participa en el "III Certamen Nacional de Bandas de
      Música Enrique García Asensio" en Minglanilla (Cuenca), obteniendo un
      meritorio tercer puesto compitiendo con bandas de gran pestigio. En este
      año inaugura el ciclo "Música entre Vinos", organizado por la Asociación
      Ruta del Vino de Jumilla, participando y colaborando en todas las
      anualidades posteriores.
    </li>
    <li>
      Desde el año 2012 hasta 2017 coorganiza el curso "Jumilla Low Brass",
      festival de referencia nacional, enfocado únicamente a la tuba y al
      bombardino.
    </li>
    <li>
      En el año 2018, se participó en el "VI Certamen de Bandas de Música Cruz
      de Humilladero Ciudad de Málaga".
    </li>
    <li>
      Esta Asociación ha publicado tres grabaciones discográficas de su Banda
      de Música: “Marchas Procesionales”, “Recuerdos Jumillanos” (pasodobles),
      todas obras de compositores jumillanos o vinculados a esta ciudad y el
      Cd "Música y Armonía Contra el Cáncer", a beneficio de la AECC.
    </li>
    <li>
      En el año 2023 participó en el certamen internacional de bandas de
      música "VILLA DE ARANDA", consiguiendo un 2º puesto
    </li>
  </ul>
</body>
<app-footer></app-footer>

// pages/about.vue
<template>
  <div>
    <h2>Sobre nosotros</h2>
    <p>
      La Asociación Jumillana Amigos de la Música fue fundada en 1980 por un
      grupo de entusiastas jumillanos, con el apoyo del Excmo. Ayuntamiento de
      Jumilla, con el fin de ocupar el espacio musical dejado por la
      desaparecida Banda de Música Municipal.
    </p>
    <p>
      Una vez constituida la Asociación, se crea una Academia de Música y con
      los alumnos formados en esta, se crea la Banda de Música de la Asociación.
      Esta hace su presentación oficial, en Jumilla el 12 de Abril de 1981. Su
      primer director fue el compositor jumillano D. Julián Santos Carrión, a
      quien sucedería en 1982 D. José Bacigalupe Serrano, desde 1987 y hasta
      1996 dirigió la Academia y Banda de la Asociación D. Antonio Milán Juan,
      durante el año 1997 D. Sergio Fernández Diez-Picazo. En 1998 D. José Ant.
      Arce Corbalán. Del 1999 al 2004 la dirigió el músico y compositor
      georgiano D. Zurab Kala al que sucedió D. Julián Andreo Jiménez hasta
      noviembre de 2008. Desde diciembre de 2008, D. Mario Ortuño Gelardo es el
      director de la Banda de Música a sí como de su Academia hasta octubre de
      2015, año en el que entraría como director de la Banda de Música Titular
      Ángel Hernández Azorín.
    </p>
    <p>
      Desde su creación, la Banda ha desarrollado una intensa actividad musical,
      participando en numerosos ciclos de conciertos en la localidad, en toda la
      región de Murcia y las Regiones limítrofes de Castilla la Mancha y
      Valencia. Participa en varios programas radiofónicos de Radio Nacional de
      España: “A TODA BANDA” y “PLAZA MAYOR”, y en programas televisivos a nivel
      regional y nacional.
    </p>
    <p>
      En 1989 se forma la Banda de Música Juvenil, con el objetivo de preparar a
      los educandos de la Academia y los integrantes noveles de la Banda de la
      Asociación.
    </p>
    <p>
      Desde el año 1983, en el mes de noviembre la Asociación viene celebrando
      una semana cultural en honor a Santa Cecilia, con actuaciones de solistas
      y grupos de reconocido prestigio, tanto nacionales como extranjeros. En
      1993, se organiza el primer Festival de Bandas de Música, con la
      participación de dos bandas invitadas y la Banda de la Asociación,
      intentando mantener un alto nivel interpretativo de cada una de las
      agrupaciones participante y de las obras elegidas.
    </p>
    <p>Entre los mayores logros obtenidos cabe destacar:</p>
    <ul>
      <li>
        En los programas - concursos de televisión española “GENTE JOVEN” y
        “NUEVA GENTE”, quedando semifinalistas en el primero de ellos.
      </li>
      <li>
        En 1997 participa en el "Festival Internacional de Bandas de Música
        Villa Altea”, junto a otras bandas de Música con reconocido prestigio
        como el Ateneo Musical de Cullera y la Sociedad Musical de Alcira,
        obteniendo el tercer premio. En el 2001 participa en la 2º sección del I
        Certamen Nacional de Zarzuela para Bandas de Música organizado por la
        Fundación Nacional de la Zarzuela, obteniendo un 2º accesit.
      </li>
      <li>
        En el año 2003 participa en el I Certamen Regional de Bandas de la
        Región de Murcia, obteniendo un segundo premio en la 1ª sección y en el
        IV Certamen Internacional de Bandas de Música “Villa de Aranda”
        obteniendo el Premio Especial al Desfile. En el año 2005 participa en el
        II Certamen Regional de Bandas de la Región de Murcia, obteniendo un
        segundo premio en la 1ª sección.
      </li>
      <li>
        En Julio de 2008 participa en el "III Certamen Nacional de Bandas de
        Música Enrique García Asensio" en Minglanilla (Cuenca), obteniendo un
        meritorio tercer puesto compitiendo con bandas de gran pestigio. En este
        año inaugura el ciclo "Música entre Vinos", organizado por la Asociación
        Ruta del Vino de Jumilla, participando y colaborando en todas las
        anualidades posteriores.
      </li>
      <li>
        Desde el año 2012 hasta 2017 coorganiza el curso "Jumilla Low Brass",
        festival de referencia nacional, enfocado únicamente a la tuba y al
        bombardino.
      </li>
      <li>
        En el año 2018, se participó en el "VI Certamen de Bandas de Música Cruz
        de Humilladero Ciudad de Málaga".
      </li>
      <li>
        Esta Asociación ha publicado tres grabaciones discográficas de su Banda
        de Música: “Marchas Procesionales”, “Recuerdos Jumillanos” (pasodobles),
        todas obras de compositores jumillanos o vinculados a esta ciudad y el
        Cd "Música y Armonía Contra el Cáncer", a beneficio de la AECC.
      </li>
      <li>
        En el año 2023 participó en el certamen internacional de bandas de
        música "VILLA DE ARANDA", consiguiendo un 2º puesto
      </li>
    </ul>
  </div>
</template>

<style scoped>
h2 {
  margin-bottom: 20px;
  font-size: 36px;
}

p {
  margin: 20px 0;
}

ul {
  text-align: left;
  list-style: square;
}
</style>
