// src/app/pages/contact/contact.component.ts
import { Component } from '@angular/core';
import { FooterComponent } from '../../footer/footer.component';

@Component({
  selector: 'app-contact',
  imports: [FooterComponent],
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.css'
})
export class ContactComponent {

}

<body>
  <h1>¡Contáctanos!</h1>
  <br>
  <p>Si tienes alguna pregunta o sugerencia, no dudes en ponerte en contacto con nosotros.</p>
  <iframe
    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d656.6508411272218!2d-1.3195273721576688!3d38.47436255408451!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd640f642becea41%3A0x89025ddc60fb8d1f!2sAsociaci%C3%B3n%20Jumillana%20Amigos%20de%20la%20M%C3%BUsica!5e0!3m2!1ses!2ses!4v1735577101620!5m2!1ses!2ses"
    allowfullscreen="false"
    loading="lazy"
    referrerpolicy="no-referrer-when-downgrade">
  </iframe>
  <br>
  <br>
  <p>Para más información, no dudes en ponerte en contacto con nosotros.</p>
  <br>
</body>
<app-footer></app-footer>

// pages/contact.vue
<template>
  <div>
    <h2>Contáctanos</h2>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ex non
      animi, delectus ad suscipit, voluptatum dicta ipsam temporibus ratione
      adipisci velit minus aliquam rem esse dolorum nihil inventore reiciendis.
    </p>
    <div class="flex gap-10">
      <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d656.6508411272218!2d-1.3195273721576688!3d38.47436255408451!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd640f642becea41%3A0x89025ddc60fb8d1f!2sAsociaci%C3%B3n%20Jumillana%20Amigos%20de%20la%20M%C3%BAsica!5e0!3m2!1ses!2ses!4v1735577101620!5m2!1ses!2ses"
        width="700"
        height="450"
        style="border: 0"
        allowfullscreen="false"
        loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"
      ></iframe>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ex non
        animi, delectus ad suscipit, voluptatum dicta ipsam temporibus ratione
        adipisci velit minus aliquam rem esse dolorum nihil inventore
        reiciendis.
      </p>
    </div>
  </div>
</template>

<style scoped>
h2 {
  margin-bottom: 20px;
  font-size: 36px;
}

p {
  margin: 20px 0;
}
</style>
